use tempfile library to handle tmp folders
When running OrthoFinder in a cluster under an NFS folder, the tests are
so fast that sometimes some internal files are still being deleted whilst
`shutil.rmtree()` is running, raising an error:
```
Traceback (most recent call last):
  File "/hps/software/users/ensembl/compara/jalvarez/testbench/OrthoFinder_source/orthofinder.py", line 7, in <module>
    main(args)
  File "/hps/software/users/ensembl/compara/jalvarez/testbench/OrthoFinder_source/scripts_of/__main__.py", line 1719, in main
    CheckDependencies(options, prog_caller, files.FileHandler.GetWorkingDirectory1_Read()[0])
  File "/hps/software/users/ensembl/compara/jalvarez/testbench/OrthoFinder_source/scripts_of/__main__.py", line 1310, in CheckDependencies
    elif not prog_caller.TestSearchMethod(dirForTempFiles, options.search_program):
  File "/hps/software/users/ensembl/compara/jalvarez/testbench/OrthoFinder_source/scripts_of/program_caller.py", line 199, in TestSearchMethod
    shutil.rmtree(d)
  File "/hps/software/users/ensembl/compara/shared/pyenv/versions/3.9.5/lib/python3.9/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/hps/software/users/ensembl/compara/shared/pyenv/versions/3.9.5/lib/python3.9/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/hps/software/users/ensembl/compara/shared/pyenv/versions/3.9.5/lib/python3.9/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: '.nfs491292b75b71b1300002134e'
```
Since this temporary folder is only meant to be alive for the time of
the test(s), I have moved this code inside a context manager using
`tempfile`. This way you let the system handle the cleanup on its own,
and gives the user more control over where the tests are run.